/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desafio12.gerhauser.Ejercicio2.Vista;

import desafio12.gerhauser.Ejercicio2.Controlador.controladoCategoria;
import desafio12.gerhauser.Ejercicio2.Controlador.controladoProducto;
import desafio12.gerhauser.Ejercicio2.DAO.DAOCategoria;
import desafio12.gerhauser.Ejercicio2.DAO.DAOProducto;
import desafio12.gerhauser.Ejercicio2.Modelo.modeloCategoria;
import desafio12.gerhauser.Ejercicio2.Modelo.modeloProducto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benja
 */
public class vistaListadoGestor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaListadoGestor.class.getName());

    /**
     * Creates new form vistaListado
     */
    public vistaListadoGestor() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        seleccionarProducto();
        seleccionarCategoria();
        listarProductos();
        ScrollPaneCat.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    int idCategoria;
    String nombreCategoria;
    
    int idProducto;
    String nombreProducto;
    String categoriaProducto;
    double precioProducto;
    int stockProducto;
    int idCategoriaProducto;
    List<modeloCategoria> listaCategorias;
    List<String> listaProductos;

    controladoProducto controladoProducto = new controladoProducto();
    controladoCategoria controladorCategoria = new controladoCategoria();
    protected void listarCategorias() {
        DefaultTableModel model = (DefaultTableModel) tableListadoCategorias.getModel();
        model.setRowCount(0);
        listaCategorias = controladorCategoria.listar();
        for (modeloCategoria categoria : listaCategorias) {
            model.addRow(new Object[]{
                String.valueOf(categoria.getId()),
                categoria.getNombre()
            });
        }
    }
    protected void listarProductos() {
        DefaultTableModel model = (DefaultTableModel) tableListadoProductos.getModel();
        model.setRowCount(0);
        listaProductos = controladoProducto.listarConCategoria();
        for (String producto : listaProductos) {
            String[] elementos = producto.split(",");
            model.addRow(new Object[]{
                elementos[0],
                elementos[1],
                elementos[2],
                elementos[3],
                elementos[4],
                elementos[5]
            });
        }
    }
    protected void seleccionarCategoria(){
        tableListadoCategorias.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = tableListadoCategorias.getSelectedRow();
                if (fila != -1) {
                    idCategoria = Integer.parseInt(tableListadoCategorias.getValueAt(fila, 0).toString());
                    nombreCategoria = tableListadoCategorias.getValueAt(fila, 1).toString();
                }
            }
        });
    }
    protected void seleccionarProducto(){
       tableListadoProductos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = tableListadoProductos.getSelectedRow();
                if (fila != -1) {
                    idProducto = Integer.parseInt(tableListadoProductos.getValueAt(fila, 0).toString());
                    nombreProducto = tableListadoProductos.getValueAt(fila, 1).toString();
                    precioProducto = Double.parseDouble(tableListadoProductos.getValueAt(fila, 2).toString());
                    stockProducto = Integer.parseInt(tableListadoProductos.getValueAt(fila, 3).toString());
                    categoriaProducto = tableListadoProductos.getValueAt(fila, 4).toString();
                    idCategoriaProducto = Integer.parseInt(tableListadoProductos.getValueAt(fila, 5).toString());
                }
            }
        }); 
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cboOpcion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ScrollPaneCat = new javax.swing.JScrollPane();
        tableListadoCategorias = new javax.swing.JTable();
        ScrollPaneProd = new javax.swing.JScrollPane();
        tableListadoProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setText("Editar Seleccionado");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 64, 200, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 6, 200, -1));

        btnEliminar.setText("Eliminar Seleccionado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 35, 200, -1));

        cboOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Categorias" }));
        cboOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOpcionActionPerformed(evt);
            }
        });
        getContentPane().add(cboOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 150, -1));

        jLabel1.setText("Listar por:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        tableListadoCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollPaneCat.setViewportView(tableListadoCategorias);

        getContentPane().add(ScrollPaneCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 500, 320));

        tableListadoProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock", "Categoria", "IDCategoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollPaneProd.setViewportView(tableListadoProductos);

        getContentPane().add(ScrollPaneProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 500, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        vistaEditar vistaEditar;
        if (cboOpcion.getSelectedItem() == "Categorias") {
            vistaEditar = new vistaEditar(idCategoria, nombreCategoria,this);
            vistaEditar.setVisible(true);
        }
        else{
            vistaEditar = new vistaEditar(idProducto,nombreProducto,precioProducto,stockProducto,idCategoriaProducto,this);
            vistaEditar.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        vistaAgregar vistaAgregar = new vistaAgregar(this);
        vistaAgregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (cboOpcion.getSelectedItem() == "Categorias") {
                controladorCategoria.eliminar(idCategoria);
                ScrollPaneCat.setVisible(true);
                ScrollPaneProd.setVisible(false);
                listarCategorias();
        }
        else{
            try {
                controladoProducto.eliminar(idProducto);
                ScrollPaneCat.setVisible(false);
                ScrollPaneProd.setVisible(true);
                listarProductos();
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cboOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOpcionActionPerformed
        if (cboOpcion.getSelectedItem() == "Categorias") {
            ScrollPaneCat.setVisible(true);
            ScrollPaneProd.setVisible(false);
            listarCategorias();
        }
        else{
            ScrollPaneCat.setVisible(false);
            ScrollPaneProd.setVisible(true);
            listarProductos();
        }
       
    }//GEN-LAST:event_cboOpcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaListadoGestor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneCat;
    private javax.swing.JScrollPane ScrollPaneProd;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tableListadoCategorias;
    private javax.swing.JTable tableListadoProductos;
    // End of variables declaration//GEN-END:variables
}
