/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desafio12.gerhauser.Ejercicio2.Vista;

import desafio12.gerhauser.Ejercicio2.Controlador.controladoCategoria;
import desafio12.gerhauser.Ejercicio2.Controlador.controladoProducto;
import desafio12.gerhauser.Ejercicio2.Modelo.modeloCategoria;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Benja
 */
public class vistaAgregar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaAgregar.class.getName());
    List<modeloCategoria> listaCategorias;  
    /**
     * Creates new form vistaAgregar
     */
    public vistaAgregar(){}
    public vistaAgregar(vistaListadoGestor vistaListado) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                vistaListado.listarProductos();
                vistaListado.listarCategorias();
            }
        });
        
        listaCategorias = controladoCategoria.listar();
        cargarComboCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboOpcion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cboCategorias = new javax.swing.JComboBox<>();
        numericPrecio = new javax.swing.JSpinner();
        numericStock = new javax.swing.JSpinner();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto", "Categoria" }));
        cboOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOpcionActionPerformed(evt);
            }
        });

        jLabel1.setText("Que quiere agregar:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblPrecio.setText("Precio");

        lblStock.setText("Stock");

        lblCategoria.setText("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboOpcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(lblNombre)
                    .addComponent(lblStock)
                    .addComponent(numericStock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCategoria)
                    .addComponent(lblPrecio)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(cboCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numericPrecio))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numericPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(lblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numericStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarComboCategoria(){
        cboCategorias.removeAllItems();
        for (modeloCategoria categoria : listaCategorias) {
            String categoriaString = categoria.getId()+ ", " + categoria.getNombre();
            cboCategorias.addItem(categoriaString);
        }
    }
    private void cboOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOpcionActionPerformed
        if (cboOpcion.getSelectedItem() == "Producto") {
            numericPrecio.setVisible(true);
            numericStock.setVisible(true);
            cboCategorias.setVisible(true);
            lblCategoria.setVisible(true);
            lblNombre.setVisible(true);
            lblPrecio.setVisible(true);
            lblStock.setVisible(true);
        }
        else{
            numericPrecio.setVisible(false);
            numericStock.setVisible(false);
            cboCategorias.setVisible(false);
            lblCategoria.setVisible(false);
            lblNombre.setVisible(false);
            lblPrecio.setVisible(false);
            lblStock.setVisible(false);
        }
    }//GEN-LAST:event_cboOpcionActionPerformed
    controladoCategoria controladoCategoria = new controladoCategoria();
    controladoProducto controladoProducto = new controladoProducto();

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (cboOpcion.getSelectedItem() == "Producto") {
            String nombre = txtNombre.getText();
            double precio = Double.parseDouble(numericPrecio.getValue().toString());
            int stock = Integer.parseInt(numericStock.getValue().toString());
            
            String categoria = cboCategorias.getSelectedItem().toString();
            int idCategoria = Integer.parseInt(categoria.split(",")[0]);
            System.out.println(idCategoria);
            
            controladoProducto.agregar(nombre, precio, stock, idCategoria);
            JOptionPane.showMessageDialog(null, "Producto Agregado");
        }else{
            String nombre = txtNombre.getText();
            controladoCategoria.agregar(nombre);
            JOptionPane.showMessageDialog(null, "Categoria Agregada");
            listaCategorias = controladoCategoria.listar();
            cargarComboCategoria();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaAgregar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cboCategorias;
    private javax.swing.JComboBox<String> cboOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JSpinner numericPrecio;
    private javax.swing.JSpinner numericStock;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
