/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desafio9.gerhauser;

/**
 *
 * @author Alumno
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstLenguajes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstLenguajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Python", "C++", "C#", "C", "Java", "JavaScript" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLenguajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLenguajes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstLenguajesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstLenguajes);
        lstLenguajes.getAccessibleContext().setAccessibleName("lstLenguajes");

        txtAreaTexto.setColumns(20);
        txtAreaTexto.setRows(5);
        txtAreaTexto.setText("...");
        jScrollPane2.setViewportView(txtAreaTexto);
        txtAreaTexto.getAccessibleContext().setAccessibleName("txtAreaTexto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstLenguajesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstLenguajesValueChanged
        if (!evt.getValueIsAdjusting()) {
            String seleccionado = lstLenguajes.getSelectedValue();
            switch (seleccionado) {
                case "Python":
                    txtAreaTexto.setText("""
                                    🐍 Python

                                    Tipo: Interpretado, de alto nivel.

                                    Usos comunes: Ciencia de datos, inteligencia artificial, automatización, desarrollo web (Django, Flask).

                                    Ventajas: Sintaxis muy simple, gran comunidad, muchas librerías.

                                    Desventajas: Más lento que los compilados, no ideal para apps móviles o de bajo nivel.
                                    """);
                    break;
                case "C++":
                    txtAreaTexto.setText("""
                                    💻 C++

                                    Tipo: Compilado, orientado a objetos y de propósito general.

                                    Usos comunes: Desarrollo de videojuegos, sistemas embebidos, software de alto rendimiento.

                                    Ventajas: Muy rápido, acceso directo a memoria, gran control sobre recursos.

                                    Desventajas: Sintaxis compleja, manejo manual de memoria.
                                    """);
                    break;
                case "C#":
                    txtAreaTexto.setText("""
                                    🧩 C# (C Sharp)

                                    Tipo: Compilado, orientado a objetos, desarrollado por Microsoft.

                                    Usos comunes: Aplicaciones de escritorio (Windows), videojuegos (Unity), desarrollo web (ASP.NET).

                                    Ventajas: Integración con el ecosistema .NET, productivo y moderno.

                                    Desventajas: Menos usado fuera del entorno Microsoft, menos multiplataforma que otros (aunque .NET Core mejoró eso).
                                    """);
                    break;
                case "C":
                    txtAreaTexto.setText("""
                                    ⚙️ C

                                    Tipo: Compilado, estructurado y de bajo nivel.

                                    Usos comunes: Sistemas operativos, drivers, software embebido.

                                    Ventajas: Muy rápido, control total del hardware, base de muchos otros lenguajes.

                                    Desventajas: No orientado a objetos, requiere manejo manual de memoria, propenso a errores de punteros.
                                    """);
                    break;
                case "Java":
                    txtAreaTexto.setText("""
                                    ☕ Java

                                    Tipo: Compilado a bytecode e interpretado por la JVM.

                                    Usos comunes: Aplicaciones empresariales, Android, backends web.

                                    Ventajas: Multiplataforma (“write once, run anywhere”), fuerte tipado, gran comunidad.

                                    Desventajas: Verboso, más consumo de memoria comparado con otros.
                                    """);
                    break;
                case "JavaScript":
                    txtAreaTexto.setText("""
                                    🌐 JavaScript

                                    Tipo: Interpretado, dinámico, multiparadigma.

                                    Usos comunes: Desarrollo web (frontend y backend con Node.js).

                                    Ventajas: Lenguaje nativo del navegador, enorme ecosistema (React, Angular, Vue).

                                    Desventajas: Inconsistencias del lenguaje, dependiente del entorno (navegador o Node).
                                    """);
                    break;
                default:
                    throw new AssertionError();
            }

        }
    }//GEN-LAST:event_lstLenguajesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstLenguajes;
    private javax.swing.JTextArea txtAreaTexto;
    // End of variables declaration//GEN-END:variables
}
